{% set name = "vodex" %}
{% set version = "1.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vodex-{{ version }}.tar.gz
  sha256: 88539e469759722a07cde8da8892c6888a8093009c66cec637e41cd15fa1643a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - numpy
    - python >=3.8
    - tifffile
    - tqdm

test:
  imports:
    - vodex
  commands:
    - pip list
    # - pip check  # Fails due to pathlib
  requires:
    - pip

about:
  home: https://github.com/LemonJust/vodex
  summary: |
    VoDEx : Volumetric Data and Experiment Manager. Allows to load
    volumetric data based on experimental conditions.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - goanpeca
    - LemonJust
