{% set name = "vodex" %}
{% set version = "1.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vodex-{{ version }}.tar.gz
  sha256: f9bd4b45e4e50c16bca6d28edf6715fd199ac2cbca3e7a1eefaba555eac0ac6f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - numpy
    - pandas
    - python >=3.8
    - tifffile
    - tqdm

test:
  imports:
    - vodex
  commands:
    - pip list
    # - pip check  # Fails due to pathlib
  requires:
    - pip

about:
  home: https://pypi.org/project/vodex
  summary: |
    VoDEx : Volumetric Data and Experiment Manager. Allows to load
    volumetric data based on experimental conditions.
  license: BSD-3-Clause
  license_file: LICENSE.md
  dev_url: https://github.com/LemonJust/vodex

extra:
  recipe-maintainers:
    - goanpeca
    - LemonJust
